CREATE TABLE `activities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`dealId` int,
	`type` varchar(50) NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `activities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `clients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`cpfCnpj` varchar(20),
	`rg` varchar(30),
	`email` varchar(320),
	`phone` varchar(30),
	`address` text,
	`birthDate` varchar(20),
	`maritalStatus` varchar(30),
	`nationality` varchar(50),
	`profession` varchar(100),
	`motherName` varchar(255),
	`fatherName` varchar(255),
	`clientRole` enum('comprador','vendedor','locador','locatario','fiador','corretor') DEFAULT 'comprador',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `clients_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contracts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`dealId` int,
	`code` varchar(30),
	`nomeVendedor` varchar(255),
	`nacionalidadeVendedor` varchar(50),
	`estadoCivilVendedor` varchar(30),
	`profissaoVendedor` varchar(100),
	`tipoDocumentoVendedor` varchar(10),
	`numeroDocumentoVendedor` varchar(50),
	`cpfCnpjVendedor` varchar(20),
	`enderecoVendedor` text,
	`nomeComprador` varchar(255),
	`nacionalidadeComprador` varchar(50),
	`estadoCivilComprador` varchar(30),
	`profissaoComprador` varchar(100),
	`tipoDocumentoComprador` varchar(10),
	`numeroDocumentoComprador` varchar(50),
	`cpfCnpjComprador` varchar(20),
	`enderecoComprador` text,
	`descricaoImovel` text,
	`matriculaImovel` varchar(50),
	`cartorioRegistroImoveis` varchar(255),
	`itensImovel` text,
	`valorTotalContrato` varchar(100),
	`modalidadePagamento` varchar(30),
	`valorPagamentoAvista` varchar(100),
	`formaPagamentoAvista` varchar(50),
	`dataPagamentoAvista` varchar(20),
	`valorFinanciamento` varchar(100),
	`instituicaoFinanceira` varchar(100),
	`descricaoImovelPermuta` text,
	`valorImovelPermuta` varchar(100),
	`ajusteFinanceiroPermuta` text,
	`prazoEntregaPosse` varchar(50),
	`condicaoEntregaPosse` text,
	`prazoEscritura` varchar(50),
	`responsavelDespesas` varchar(50),
	`quantidadeExerciciosIptu` varchar(10),
	`prazoCertidaoObjetoPe` varchar(50),
	`prazoRestituicaoValores` varchar(50),
	`percentualComissao` varchar(20),
	`valorComissao` varchar(100),
	`percentualMulta` varchar(20),
	`condicoesDistrato` text,
	`plataformaAssinatura` varchar(50),
	`razaoSocialImobiliaria` varchar(255),
	`cnpjImobiliaria` varchar(20),
	`creciImobiliaria` varchar(30),
	`enderecoImobiliaria` text,
	`foroEleito` varchar(100),
	`cidadeAssinatura` varchar(100),
	`dataAssinatura` varchar(20),
	`nomeTestemunha1` varchar(255),
	`cpfTestemunha1` varchar(20),
	`nomeTestemunha2` varchar(255),
	`cpfTestemunha2` varchar(20),
	`pdfUrl` text,
	`pdfKey` varchar(500),
	`contractStatus` enum('rascunho','gerado','enviado','assinado') DEFAULT 'rascunho',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contracts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `deals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`code` varchar(20) NOT NULL,
	`type` enum('venda','locacao','permuta','financiamento') NOT NULL,
	`subtype` varchar(50),
	`status` enum('rascunho','em_andamento','contrato_gerado','assinatura','concluido') NOT NULL DEFAULT 'rascunho',
	`sellerId` int,
	`buyerId` int,
	`propertyId` int,
	`brokerId` int,
	`totalValue` decimal(15,2),
	`monthlyValue` decimal(15,2),
	`paymentModality` varchar(50),
	`notes` text,
	`docsTotal` int DEFAULT 7,
	`docsCompleted` int DEFAULT 0,
	`progressPct` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `deals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`dealId` int,
	`clientId` int,
	`name` varchar(255) NOT NULL,
	`docType` enum('rg','cpf','cnh','comprovante_residencia','matricula','iptu','certidao','contrato','outro') DEFAULT 'outro',
	`fileUrl` text,
	`fileKey` varchar(500),
	`mimeType` varchar(100),
	`fileSize` int,
	`ocrStatus` enum('pending','processing','done','failed') DEFAULT 'pending',
	`ocrText` text,
	`ocrFields` json,
	`ocrConfidence` int,
	`docStatus` enum('pendente','extraido','validado','rejeitado') DEFAULT 'pendente',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `properties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`description` text,
	`street` varchar(255),
	`number` varchar(20),
	`complement` varchar(100),
	`neighborhood` varchar(100),
	`city` varchar(100),
	`state` varchar(2),
	`zipCode` varchar(10),
	`registration` varchar(50),
	`registryOffice` varchar(255),
	`area` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `properties_id` PRIMARY KEY(`id`)
);
